import {
  NAV_LINKS,
  MOBILE_MAIN_NAV,
  MOBILE_NAV_FOOTER,
  DOCUMENTATION_LINKS,
} from "./navigation_links";

import { CONTACT_DETAILS } from "./site_data.jsx";

import { WHY_CHOOSE_US } from "./home_text";

import { PRE_SALE_DETAILS, MAIN_SALE_DETAILS } from "./token_sale.js";

import { ROADMAP_DATA } from "./roadmap.js";

import {
  TOKEN_DISTRIBUTIION_BREAKDOWN,
  TOKEN_UTILITY_AND_FUNCTIONALITY,
  ECONOMIC_INCENTIVES_AND_VALUE_PRESERVATION,
  LONG_TERM_SUSTAINABILITY_AND_CONPLIANCE,
} from "./tokenomics.js";

import { TEAM_DATA } from "./about.js";

import {
  AUDIT_REPORTS_DOCS,
  LEGAL_DISCLAIMERS_DOCS,
  LITEPAPER_DOCS,
  RISK_DISCLOSURES_DOCS,
  TOKEN_PURCHASE_AGREEMENTS_DOCS,
  WHITEPAPER_DOCS,
} from "./documentation";

const text_data = {
  NAV_LINKS,
  MOBILE_MAIN_NAV,
  MOBILE_NAV_FOOTER,
  DOCUMENTATION_LINKS,
  CONTACT_DETAILS,
  WHY_CHOOSE_US,
  TEAM_DATA,
  PRE_SALE_DETAILS,
  MAIN_SALE_DETAILS,
  ROADMAP_DATA,
  TOKEN_DISTRIBUTIION_BREAKDOWN,
  TOKEN_UTILITY_AND_FUNCTIONALITY,
  ECONOMIC_INCENTIVES_AND_VALUE_PRESERVATION,
  LONG_TERM_SUSTAINABILITY_AND_CONPLIANCE,
  AUDIT_REPORTS_DOCS,
  LEGAL_DISCLAIMERS_DOCS,
  LITEPAPER_DOCS,
  RISK_DISCLOSURES_DOCS,
  TOKEN_PURCHASE_AGREEMENTS_DOCS,
  WHITEPAPER_DOCS,
};

export default text_data;
